# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    published:
        label: 是否发布
        type: group
        conditions: published in (:filtered)
        options:
            0: 否
            1: 是
    # published:
    #     label: toggle
    #     type: switch
    #     default: 1
    #     conditions:
    #         - published = 1
    name:
        label: 名称
        type: text
        conditions: name = :value
