# ===================================
#  Form Behavior Config
# ===================================

name: Phone
form: ~/Modules/Test/Models/phone/fields.yaml
modelClass: Modules\Test\Models\Phone
defaultRedirect: test/phone

create:
    redirect: test/phone/update/:id
    redirectClose: test/phone

update:
    redirect: test/phone
    redirectClose: test/phone
